app/views.py
import os
import re
from datetime import datetime
from utils import status_code
from utils.functions import random_check_code, is_login
from flask import Blueprint, request, render_template,\
    redirect, url_for, jsonify, session
from werkzeug.security import generate_password_hash, check_password_hash

from app.form import UserRegisterForm
from app.models import User, db, House, Facility, HouseImage, Order
from utils.settings import MEDIA_PATH, UPLOAD_DIR

blue = Blueprint('user', __name__)


# +++++++++++++++++++++++++++++++++++++++++++++登录注册主页++++++++++++++++++++++++++++++++++++++++++++++++++
@blue.route('/create_db/')
def create_db():
    db.create_all()
    return 'success'


# 注册
@blue.route('/register/', methods=['GET', 'POST'])
def register():

    if request.method == 'GET':
        check_code = random_check_code()
        return render_template('register.html',check_code=check_code)

    if request.method == 'POST':
        mobile = request.form.get('mobile')
        imagecode = request.form.get('imagecode')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if mobile:
            pass
        else:
            return jsonify({'code': 10001, 'msg': '该手机号已注册'})
        if imagecode == session['check_code']:
            pass
        else:
            return jsonify({'code': 10002, 'msg': '验证码错误'})
        if password == password2:
            # 保存
            user = User()
            user.phone = mobile
            user.pwd_hash = generate_password_hash(password)
            user.add_update()
            return jsonify({'code':200, 'msg': '注册成功'})
        else:
            return jsonify({'code':10003, 'msg': '密码不一致'})


# 登录
@blue.route('/login/', methods=['GET'])
def login():
    if request.method == 'GET':
        return render_template('login.html')


@blue.route('/login/', methods=['POST'])
def my_login():
    if request.method == 'POST':
        mobile = request.form.get('mobile')
        password = request.form.get('password')
        # 校验字段的完整性
        if not all([mobile, password]):
            return jsonify({'code': 10001, 'msg': '请填写完整参数'})
        # 判断用户是否注册
        user = User.query.filter(User.phone==mobile).first()
        if not user:
            return jsonify({'code': 10002, 'msg': '用户没有注册请去注册'})
        # 校验密码
        if not check_password_hash(user.pwd_hash, password):
            return jsonify({'code': 10003, 'msg': '密码不正确'})
        session['user_id'] = user.id
        user_avatar = user.avatar
        return jsonify({'code': 200, 'msg': '请求成功'})


# app主页
@blue.route('/index/')
def index():
    try:
        if session['user_id']:
            user = User.query.filter(User.id == session['user_id']).first()
            return render_template('index.html', user=user )
    except:
        return render_template('login.html')


@blue.route('/index_info/')
def index_info():
    latest_three_house = House.query.filter().order_by('-id')[0:3]
    three_house = [house.to_dict() for house in latest_three_house]
    return jsonify(code=status_code.SUCCESS, three_house=three_house)


# 注销
@blue.route('/logout/', methods=['GET'])
@is_login
def user_logout():
    session.clear()
    # return redirect(url_for('user.login'))
    return jsonify(status_code.SUCCESS)
# +++++++++++++++++++++++++++++++++++++++++++++++用户界面++++++++++++++++++++++++++++++++++++++++++++++++++++++++


# 用户主页
@blue.route('/my/', methods=['GET', 'POST'])
@is_login
def my():
    if request.method == 'GET':
        if session['user_id']:
            user = User.query.filter(User.id == session['user_id']).first()
            return render_template('my.html', name=user.name, mobile=user.phone, avatar=user.avatar)
        else:
            return render_template('login.html')


# 用户信息修改
@blue.route('/profile/', methods=['GET', 'POST'])
@is_login
def profile():
    if request.method == 'GET':
        user = User.query.filter(User.id == session['user_id']).first()
        return render_template('profile.html', user=user)

    if request.method == 'POST':
        name = request.form.get('username')
        avatar = request.files.get('avatar')
        if avatar:
            path = os.path.join(MEDIA_PATH, avatar.filename)
            avatar.save(path)
            user = User.query.filter(User.id==session['user_id']).first()
            user.avatar = avatar.filename
            user.add_update()
            return jsonify({'code': 200, 'msg': '保存成功'})
        if name:
            user = User.query.filter(User.id == session['user_id']).first()
            user.name = name
            user.add_update()
            return jsonify({'code': 200, 'msg': '保存成功'})


# 实名认证
@blue.route('/auth/', methods=['GET', 'POST'])
@is_login
def auth():
    if request.method == 'GET':
        user = User.query.filter(User.id == session['user_id']).first()
        real_name = user.id_name
        id_card = user.id_card
        if ([real_name, id_card]):
            return render_template('auth.html', user=user, real_name=real_name, id_card=id_card)

    if request.method == 'POST':
        real_name = request.form.get('real_name')
        id_card = request.form.get('id_card')

        if not all([real_name, id_card]):
            return jsonify({'code':10001, 'msg':'请输入完整信息'})

        if not re.match(r'^[1-9]\d{17}$', id_card):
            return jsonify({'code':10002, 'msg':'身份证不符合规范'})

        user = User.query.get(session['user_id'])
        user.id_name = real_name
        user.id_card = id_card
        user.add_update()
        return jsonify({'code': 200, 'msg': '信息上传成功'})


# 我的房源
@blue.route('/myhouse/', methods=['GET'])
@is_login
def myhouse():
    if request.method == 'GET':
        user = User.query.filter(User.id == session['user_id']).first()
        real_name = user.id_name
        id_card = user.id_card
        if real_name != '' and id_card != '':
            return render_template('myhouse.html', auth=1)
        else:
            return render_template('myhouse.html', unauth=1)


# 我的房源简单信息
@blue.route('/house_info/', methods=['GET'])
@is_login
def house_info():
    user = User.query.get(session['user_id'])
    if user.id_card:
        # 实名认证成功
        houses = House.query.filter(House.user_id == session['user_id']).order_by('-id')
        houses_list = [house.to_dict() for house in houses]
        return jsonify({'code': 200, 'houses_list': houses_list})
    else:
        return jsonify({'unauth':1})


# 发布新房源
@blue.route('/newhouse/', methods=['GET', 'POST'])
@is_login
def newhouse():
    if request.method == 'GET':
        return render_template('newhouse.html')

    if request.method == 'POST':
        house_dict = request.form

        house = House()
        house.user_id = session['user_id']
        house.area_id = house_dict.get('area_id')  # 所在城区
        house.title = house_dict.get('title')  # 房屋标题
        house.price = house_dict.get('price')  # 每晚入住价格
        house.address = house_dict.get('address')  # 详细地址
        house.room_count = house_dict.get('room_count')  # 出租房间数目
        house.acreage = house_dict.get('acreage')  # 房屋面积
        house.unit = house_dict.get('unit')  # 户型描述
        house.capacity = house_dict.get('capacity')  # 宜住人数
        house.beds = house_dict.get('capacity')  # 卧床配置
        house.deposit = house_dict.get('deposit')  # 押金数额
        house.min_days = house_dict.get('min_days')  # 最少入住天数
        house.max_days = house_dict.get('max_days')  # 最多入住天数

        facilitys = house_dict.getlist('facility')
        for facility_id in facilitys:
            facility = Facility.query.get(facility_id)
            house.facilities.append(facility)
        house.add_update()
        return jsonify({'code':200, 'house_id': house.id})


# 新房源图片
@blue.route('/house_images/', methods=['POST'])
@is_login
def house_images():
    # 创建房屋图片
    house_id = request.form.get('house_id')
    image = request.files.get('house_image')

    # 保存图片  /static/media/upload/xxx.jpg
    save_url = os.path.join(UPLOAD_DIR, image.filename)
    image.save(save_url)
    # 保存房屋和图片信息
    house_image = HouseImage()
    house_image.house_id = house_id
    image_url = os.path.join('upload', image.filename)
    house_image.url = image_url
    house_image.add_update()
    # 创建房屋首图
    house = House.query.get(house_id)
    if not house.index_image_url:
        house.index_image_url = image_url
        house.add_update()
    return jsonify({'code':200, 'image_url':image_url})


# 房屋详细
@blue.route('/detail/', methods=['GET'])
def detail():
    return render_template('detail.html')


@blue.route('/house_detail/<int:id>/', methods=['GET'])
def house_detail(id):
    house = House.query.get(id)
    house_info = house.to_full_dict()
    booking = 1
    try:
        if session['user_id']:
            if house.user_id == session['user_id']:
                return jsonify(code=status_code.OK, house_info=house_info)
            else:
                return jsonify(code=status_code.OK, house_info=house_info, booking=booking)
    except:
        return jsonify(code=status_code.OK, house_info=house_info, booking=booking)


# +++++++++++++++++++++++++++++++++++++++++++++订单++++++++++++++++++++++++++++++++++++++++++++++++++


# 预定页面
@blue.route('/booking/', methods=['GET'])
@is_login
def booking():
    if request.method == 'GET':
        return render_template('booking.html')


@blue.route('/booking_info/', methods=['GET', 'POST'])
def booking_info():
    if request.method == 'GET':
        house_id = request.form.get('id')
        house_info = House.query.filter(id=house_id).to_full_dict()
        return jsonify({'code': 200, 'house_info': house_info})

    if request.method == 'POST':
        begin_date = datetime.strptime(request.form.get('begin_date'), '%Y-%m-%d')
        end_date = datetime.strptime(request.form.get('end_date'), '%Y-%m-%d')
        user_id = session['user_id']
        house_id = request.form.get('house_id')
        house = House.query.get(house_id)
        house_price = house.price

templates/auth.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-实名认证</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/profile.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">实名认证</h3>
                <a class="nav-btn fl" href="/my.html"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="menus-con">
            <ul class="menus-list">
                <li>
                    <div class="menu-title">
                        <h3>认证信息</h3>
                    </div>
                    <div class="menu-content">
                        <form id="form-auth" method="post">
                            <div class="form-group">
                                <label for="real-name">真实姓名</label>
                                <input type="text" class="form-control" name="real_name" id="real-name"  {% if real_name %} disabled="disabled" value="{{ real_name }}" {% endif %}>
                            </div>
                            <div class="form-group">
                                <label for="id-card">身份证号码</label>
                                <input type="text" class="form-control" name="id_card" id="id-card" {% if id_card %} disabled="disabled" value="{{ id_card }}" {% endif %}>
                            </div> 
                            <div class="error-msg"><i class="fa fa-exclamation-circle"></i>信息填写不完整，请补全信息</div>
                            <input type="submit" class="btn btn-success" value="保存" {% if id_card and real_name %} style="display:none" {% endif %}>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
        <div class="popup_con">
            <div class="popup">
                <p>保存成功！</p>
            </div>
            
            <div class="mask"></div>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div> 
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/jquery.form.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <!--<script src="/static/js/ihome/auth.js"></script>-->
    <script>

        $('#form-auth').submit(function(e){
            e.preventDefault()
            $(this).ajaxSubmit({
                url:'/user/auth/',
                dataType:'json',
                type:'POST',
                success:function(data){
                    if(data.code == '200'){
                        location.href='/user/my/'
                    }
                }
            })
        })
    </script>
</body>
</html>

templates/detail.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-房间信息</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/swiper/css/swiper.min.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/detail.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">房间信息</h3>
                <a class="nav-btn fl" href="#" onclick="hrefBack();"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="swiper-container">
            <ul class="swiper-wrapper">
            </ul>
            <div class="swiper-pagination"></div>
            <div class="house-price">￥<span>300</span>/晚</div>
        </div>
        <div class="detail-con">
            <div class="detail-header layout-style">
                <h2 class="house-title">房屋标题</h2> 
                <div class="landlord-pic"><img src="/static/images/landlord01.jpg"></div>
                <h2 class="landlord-name">房东： <span>房东姓名</span></h2>
            </div>
            <div class="house-info layout-style">
               <h3>房屋地址</h3>
               <ul class="house-info-list text-center">
                    <li class="address">地址内容中关村</li>
               </ul>
            </div>
            <ul class="house-type layout-style">
                <li>
                    <span class="icon-house"></span>
                    <div class="icon-text">
                        <h3>出租6间</h3>
                        <p class="acreage">房屋面积:200平米</p>
                        <p class="unit">房屋户型:三室两厅两卫</p>
                    </div>
                </li>
                <li>
                    <span class="icon-user"></span>
                    <div class="icon-text">
                        <h3 class="capacity">宜住10人</h3>
                    </div>
                </li>
                <li>
                    <span class="icon-bed"></span>
                    <div class="icon-text">
                        <h3>卧床配置</h3>
                        <p class="beds">双人床两张</p>
                    </div>
                </li>
            </ul> 
            <div class="house-info layout-style">
                <h3>房间详情</h3>
                <ul class="house-info-list">
                    <li class="deposit">收取押金<span>2000</span></li>
                    <li class="max_days">最少入住天数<span>1</span></li>
                    <li class="min_days">最多入住天数<span>无限制</span></li>
                </ul>
            </div>
            <div class="house-facility layout-style">
                <h3>配套设施</h3>
                <ul class="house-facility-list clearfix">

                </ul>
            </div> 
            <div class="house-info layout-style">
                <h3>评价信息</h3>
                <ul class="house-comment-list">
                    <li>
                        <p>用户名<span class="fr">2016-11-11 20:00:00</span></p>
                        <p>感觉不错</p>
                    </li>
                </ul>
            </div>
        </div>
        <a class="book-house" href="{{ url_for('user.booking') }}" >即刻预定</a>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div>
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/swiper/js/swiper.jquery.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script>
    var info = location.search
    house_id = info.split('=')[1]
    $.get('/user/house_detail/' + house_id + '/', function(msg){
        var images = msg.house_info.images;
        for(var i=0; i < images.length; i += 1){
            var li = '<li class="swiper-slide"><img style="width: 100%; height: 100%; max-height: 1080px; min-height: 800px" src="/static/media/' + images[i] + '"></li>';
            $('.swiper-wrapper').append(li)
        }

        var mySwiper = new Swiper ('.swiper-container', {
        loop: true,
        autoplay: 2000,
        autoplayDisableOnInteraction: false,
        pagination: '.swiper-pagination',
        paginationType: 'fraction'
    })

        facility = msg.house_info.facilities
        for (var i=0; i <facility.length; i+=1){
            var fac_css = facility[i].css;
            var fac_name = facility[i].name;
            var li = '<li><span class="' + fac_css +'"></span>'+ fac_name +'</li>';
            $('.clearfix').append(li)

        }

        $('.house-title').text(msg.house_info.title)
        $('.landlord-pic img').attr('src', '/static/media/' + msg.house_info.user_avatar)
        $('.landlord-name span').text(msg.house_info.user_name)
        $('.address').text(msg.house_info.address)
        $('.house_room').text('出租'+msg.house_info.room_count+'间')
        $('.acreage').text('房屋面积:'+msg.house_info.acreage+'平米')
        $('.unit').text(msg.house_info.unit)
        $('.capacity').text('宜住人数'+msg.house_info.capacity+'人')
        $('.beds').text(msg.house_info.beds+'张床')
        $('.deposit').text('收取押金' + msg.house_info.deposit + '元')
        $('.max_days').text('最少入住天数' + msg.house_info.min_days + '天')
        $('.min_days').text('最多入住天数' + msg.house_info.max_days + '天')
        if(msg.booking){
        $('.book-house').show();
        }
        $('.book-house').attr('href', '/user/booking/?house_id=' + msg.house_info.id)
    });
    </script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-登陆</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/login.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="logo-bar"><a href="/"><img src="/static/images/logo@128x59.png"></a></div>
        <form class="form-login">
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-user fa-lg fa-fw"></i></div>
                    <input type="number" class="form-control" name="mobile" id="mobile" placeholder="手机号" required>
                </div>
            </div>
            <div class="error-msg" id="mobile-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-lock fa-lg fa-fw"></i></div>
                    <input type="password" class="form-control" name="password" id="password" placeholder="密码" required>
                </div>
            </div>
            <div class="error-msg" id="password-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <button type="submit" class="btn btn-lg btn-theme btn-block">登录</button>
            <p class="register-a">没有账号，<a href="{{ url_for('user.register') }}">立即注册</a></p>
        </form>
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/js/ihome/login.js"></script>
    <script>
        $('.form-login').submit(function (e){
            e.preventDefault();
            var mobile = $('#mobile').val()
            var password = $('#password').val()
            $.ajax({
                url:'/user/login/',
                data:{'mobile': mobile, 'password': password},
                dataType:'json',
                type:'POST',
                success: function(data){
                        location.href='/user/index/'
                        return '登录成功'
                },
                error: function(data){
                    alert('登录失败')
                },
            })
        });
    </script>
</body>
</html>

templates/my.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-我的爱家</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/my.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">我的爱家</h3>
                <a class="nav-btn fl" href="/"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="menus-con">
            <ul class="menus-list">
                <li>
                    <div class="menu-title">
                        <h3>个人信息</h3>
                        <a class="fr" href="{{ url_for('user.profile') }}">修改</a>
                    </div>
                    <div class="menu-content">
                        <img id="user-avatar" src="/static/media/{{ avatar }}">
                        <div class="menu-text">
                            <h3>用户名：<span id="user-name">{{ name }}</span></h3>
                            <h5>手机号：<span id="user-mobile">{{ mobile }}</span></h5>
                        </div> 
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{ url_for('user.orders') }}"><h3>我的订单</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{ url_for('user.auth') }}"><h3>实名认证</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{ url_for('user.myhouse') }}"><h3>我的房源</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{ url_for('user.lorders') }}"><h3>客户订单</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="#" onclick="logout();" >退出</a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div> 
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/my.js"></script>
</body>
</html>

templates/myhouse.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-我的房源</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/myhouse.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">我的房源</h3>
                <a class="nav-btn fl" href="/my.html"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="houses-con">
            <div {% if auth %} style="display:none" {% endif %}>
            <ul class="houses-list auth-warn" >
                <li>
                    <div class="house-title">
                        <h3>尚未进行实名认证，无法发布房屋信息！</h3>
                    </div>
                    <div class="house-content">
                        <a href="{{ url_for('user.auth') }}" class="btn btn-success">去实名认证</a>
                    </div>
                </li>
            </ul>
            </div>
            <ul id="houses-list" class="houses-list" {% if unauth %} style="display:none" {% endif %}>
                <li>
                    <div class="new-house">
                        <a href="{{ url_for('user.newhouse') }}">发布新房源</a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div> 
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <!--<script src="/static/js/ihome/myhouse.js"></script>-->
    <script>

$(document).ready(function(){
    $(".auth-warn").show();

    $.get('/user/house_info/', function(data){
        if(data.code == '200'){
            $('.auth-warn').hide()
            for(var i=0; i<data.houses_list.length; i++){

                var house_li = ''
                house_li += '<li><a href="/user/detail/?house_id=' + data.houses_list[i].id + '"><div class="house-title">'
                house_li += '<h3>房屋ID:'+ data.houses_list[i].id +' —— ' + data.houses_list[i].title + '</h3></div>'
                house_li += '<div class="house-content">'
                house_li += '<img src="/static/media/' + data.houses_list[i].image + '" alt="">'
                house_li += '<div class="house-text"><ul>'
                house_li += '<li>位于：' + data.houses_list[i].area + '</li>'
                house_li += '<li>价格：￥' + data.houses_list[i].price + '/晚</li>'
                house_li += '<li>发布时间：' + data.houses_list[i].create_time + '</li>'
                house_li += '</ul></div></div></a></li>'

                $('#houses-list').append(house_li)
            }

        }else{
           $('#houses-list').hide()
        }
    });
})
    </script>
</body>
</html>